<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>alz</string>
		<string>alzheimer</string>
	</array>
	<key>name</key>
	<string>Alzheimer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b([0-9,\.]+)\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([\S]+(?=\())</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|endif|while|endwhile|break|continue|return|type|end|import)\b</string>
			<key>name</key>
			<string>keyword.alzheimer</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$\:|fun:|asm:)</string>
			<key>name</key>
			<string>keyword.alzheimer.funasms</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([\:]\b.+?\b)</string>
			<key>name</key>
			<string>keyword.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\;|\:)</string>
			<key>name</key>
			<string>keyword.alzheimer.separators</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(trace|log|print)\b</string>
			<key>name</key>
			<string>constant.numeric.line-number.find-in-files</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|gvar)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\#.*$)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.character</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\@[^\s]+)</string>
			<key>name</key>
			<string>storage.type.tag</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.alzheimer</string>
	<key>uuid</key>
	<string>e67d99a0-6c87-49b3-a8a2-d0404f93cbe0</string>
</dict>
</plist>
